### ISSUE TITLE
横制御単体動作確認用のモジュール作成(提案)

### ISSUE THREAD

**Issue by KariControl** [AutomotiveAIChallenge/autoware-practice#38]
・懸念点
Autowareの動作を理解するにあたり、横制御単体動作を理解するための横制御単体モジュールと例題(課題)もあった方が初学者の理解も進むと思われる。

・提案事項
カーブ時のプロファイルデータ(ウェイポイントの曲率情報を含むcsv)を目標軌跡とする横制御単体のモジュールを作成する。車速に関しては目標車速をlongitudinal.speedにて一定車速として与える。

**Comment by masahiro-kubota** [comment]
ありがとうございます！
こちらhttps://github.com/AutomotiveAIChallenge/autoware-practice/pull/32 がマージされたのでクローズさせていただきます。
ありがとうございました！
