### ISSUE TITLE
シェルスクリプトによる一括実行

### ISSUE THREAD

**Issue by KariControl** [AutomotiveAIChallenge/autoware-practice#40]
・懸念点
purepursuitやPID制御の例題を実行する際に、複数のノードとターミナル立ち上げが必要となる。手動で実施する場合にやや手順が多く、操作ミス(実行順番やコマンドミス等)をしやすい可能性がある。

・提案
複数ノードを自動起動するためのシェルスクリプトを用意しておき、初学者が取り組む際の操作を簡略化する。例えば、purepursuitの例題の場合は下記のようなシェルスクリプト(run.sh)を用意しておき、操作簡略化・実行順番の明示化をする。

``source install/setup.bash
``
``
gnome-terminal` -- ros2 launch autoware_practice_launch practice.launch.xml
``
``
gnome-terminal -- ros2 run plotjuggler plotjuggler
``
``
sleep 60s # plotjugglerの設定するための待機時間
``
``
gnome-terminal -- ros2 run autoware_practice_course trajectory_loader --ros-args -p 
path_file:=src/autoware_practice_course/config/trajectory_zigzag.csv
``
``
gnome-terminal -- ros2 run autoware_practice_course trajectory_follower --ros-args -p kp:=5.0 -p lookahead_distance:=5.0
``

必達ではないと思いますが、必要ならプルリクエストします。

**Comment by masahiro-kubota** [comment]
ありがとうございます！
返信が遅くなってしまい大変申し訳ありません。

是非シェルスクリプトを作成していただきたいです！
特に既に完成している2章に関して作成して頂きたいです！

提案なのですが、シェルスクリプトをautoware_pracitice_cource のスクリプトとして install して`ros2 run autoware_practice_course hoge.sh`
で実行できるようにするのはいかがでしょうか。
ノードやスクリプトを一貫した方法で実行することができるようになります！

シェルスクリプトをautoware-practice/src/autoware_pracitice_cource/src/velocity_planning/scripts/hoge.shに置いて、
autoware-practice/src/autoware_pracitice_cource/CMakelists.txtに
```
install(PROGRAMS
  src/velocity_planning/scripts/hoge.sh
  DESTINATION lib/${PROJECT_NAME}
)
```
を追加するとできると思います！

[ドキュメント](https://github.com/AutomotiveAIChallenge/aichallenge-documentation/blob/main/docs/course/velocity_planning.md)の方にも「このような便利なシェルスクリプトを用意しました！」のような文言を追加修正していただけると大変ありがたいです！

是非よろしくお願いします！
